#!/usr/bin/env python3
import os
import sys

sys.path.insert(0, os.path.abspath(".."))

from smbus3 import __version__

# -- General configuration ------------------------------------------------
needs_sphinx = "7.0"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["sphinx.ext.autodoc", "sphinx.ext.intersphinx", "sphinx.ext.extlinks"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "smbus3"
doc_title = f"{project} Documentation"
author = "Elliott Indiran"
copyright = f"2024, {author}"
# The short X.Y version.
version = __version__
# The full version, including alpha/beta/rc tags.
release = __version__
ol_description = (
    "smbus3 is a drop-in replacement for smbus2, smbus-cffi, smbus-python "
    + "written in pure Python, intended for use with Python 3.8+"
)
gr_category = "Miscellaneous"
# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"
# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__,__str__,__iter__,__repr__",
    "private-members": "_get_funcs,_set_address",
    "undoc-members": False,
    "exclude-members": "__weakref__,addr,flags,len,buf",
}

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = "alabaster"
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    "**": [
        "about.html",
        "navigation.html",
        "relations.html",
        "searchbox.html",
    ]
}
extlinks = {
    "git_tag": ("https://github.com/eindiran/smbus3/tree/%s", "%s"),
    "bug": ("https://github.com/eindiran/smbus3/issues/%s", "#%s"),
    "feature": ("https://github.com/eindiran/smbus3/issues/%s", "#%s"),
    "issue": ("https://github.com/eindiran/smbus3/issues/%s", "#%s"),
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "smbus3doc"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    "papersize": "letterpaper",
    # The font size ('10pt', '11pt' or '12pt').
    "pointsize": "10pt",
    # Latex figure (float) alignment
    "figure_align": "htbp",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "smbus3.tex", doc_title, author, "manual"),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_section = 1
man_pages = [(master_doc, project, doc_title, [author], man_section)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        project,
        doc_title,
        author,
        project,
        ol_description,
        gr_category,
    ),
]

# Configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {"python": ("https://docs.python.org/3/", None)}
