name: Build Sphinx documentation

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install setuptools
          pip install .
      - name: Build docs with Sphinx
        run: |
          cd doc
          sphinx-build -W -b html -d ./doctrees . ./html
          sphinx-build -W -b man -d ./doctrees . ./man
